[tool.poetry]
name = "MyProject"
version = "0.1.0"
description = "My project description"
authors = ["KRunchPL <krunchfrompoland@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/KRunchPL/my-project"
repository = "https://github.com/KRunchPL/my-project"
documentation = "https://github.com/KRunchPL/my-project"
license = "Apache-2.0"
packages = [
    { include = "my_project" },
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
darglint = "^1.8.1"
flake8 = "^6.1.0"
flake8-html = "^0.4.3"
flake8-isort = "^6.1.0"
flake8-pydocstyle = "^0.2.2"
flake8-pyproject = "^1.2.3"
flake8-todo = "^0.7"
pytest = "^7.4.2"
pytest-cov = "^4.1.0"
pytest-mock = "^3.11.1"
mypy = "^1.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
addopts = """
--cov my_project \
--cov-report html:coverage-report \
--cov-report term:skip-covered \
--cov-fail-under=99 \
--no-cov-on-fail \
-Werror -Wignore::ImportWarning \
--strict-markers \
"""

[tool.flake8]
count = true
max-line-length = 110
format = "html"
htmldir = "flake8-report"
extend-exclude = ".*/"
### Default ignores are far too wide
# W503: Line break occurred before a binary operator (deprecated according to PEP8)
ignore = ["W503"]
### darglint
docstring_style = "sphinx"
strictness = "full"
# Additional ignoring
# DAR401: The docstring is missing an exception raised.
#         This feature needs further investigation and can be enabled later.
extend-ignore = ["DAR401"]

[tool.isort]
virtual_env = ".venv"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
lines_between_types = 0
lines_between_sections = 1
lines_after_imports = 2
lines_before_imports = 0
include_trailing_comma = true
use_parentheses = true
multi_line_output = 3
line_length = 110
force_grid_wrap = 0
ensure_newline_before_comments = true
combine_as_imports = true
order_by_type = false

[tool.pydocstyle]
### Ignoring explanation
# D104 - Missing docstring in public package
# D107 - Missing docstring in __init__
# D200 - One-line docstring should fit on one line with quotes
# D203 - 1 blank line required before class docstring
# D212 - Multi-line docstring summary should start at the first line
ignore = """
D104,D107,
D200,D203,D212
"""

[tool.mypy]
files = "."
show_error_codes = true
# Categories below are based on mypy==1.5.1
# Default values
disallow_any_unimported = false
disallow_any_expr = false
disallow_any_decorated = false
disallow_any_explicit = false
implicit_optional = false
strict_optional = true
warn_no_return = true
ignore_errors = false
allow_untyped_globals = false
allow_redefinition = false
local_partial_types = false
strict_concatenate = false
# Strict options
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true
extra_checks = true
# Additional options
warn_unreachable = true

[[tool.mypy.overrides]]
module = [
    "tests.*",
]
disallow_untyped_defs = false
disallow_incomplete_defs = false

[[tool.mypy.overrides]]
module = [
    "tests.*.conftest",
]
disallow_untyped_defs = false
disallow_incomplete_defs = false
